productly/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls'))
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index, name='index'),
    path('form', views.form, name='form'),
    path('<int:product_id>', 
    views.detail, 
    name='detail'
    ),

]

products/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    stock = models.IntegerField()
    score = models.FloatField()
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )
    created_in = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

products/forms.py
from . import models
from django.forms import ModelForm

class ProductForm(ModelForm):
    class Meta:
        model = models.Product
        fields = ['name', 'stock', 'score', 'category']

productly/views.py
from django.shortcuts import render

def home(request):
    return render (
        request,
        'home.html',
    )

products/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from .forms import ProductForm
from .models import Product 

# Create your views here.


def index(request):
    products = Product.objects.all()
    print(products)  # Agrega este mensaje de depuración
    return render(
        request,
        'index.html',
        context={'products': products}
    )

def detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    
    return render(
        request, 
        'detail.html',
        context={ 'product': product})
    
def form(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/products')
    else:
        form = ProductForm()

    return render(
        request,
        'Product_from.html',
        {'form': form}
    )

products/templates/Product_from.html
{% extends 'base.html' %} 
{% block content %}

<form 
    novalidate 
    action="{% url 'products:form' %}" 
    method="post">
    {% csrf_token %} 
    {{ form }}
    <input type="submit" value="Enviar" />
</form>
{% endblock %}

products/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h6>{{ product.name }}</h6>
    <p>{{ product.category }}</p>
    <p>{{ product.stock }}</p>
    <p>{{ product.score }}</p>
    <p>{{ product.created_in }}</p>
</div>
{% endblock %}

products/templates/index.html
{% extends 'base.html' %} {% block content %}

<h1>Productos</h1>
<a href="{% url 'products:form' %}">New product</a>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Stock</th>
      <th>Score</th>
      <th>Category</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
    <tr>
      <td>
        <a href="{% url 'products:detail' product.id %}">
          {{ product.name }}
        </a>
      </td>
      <td>{{ product.stock }}</td>
      <td>{{ product.score }}</td>
      <td>{{ product.category }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Productly</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'home' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'products:index' %}">Products</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %}class="form-label">{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}

templates/django/forms/widgets/input.html
<input 
    class="form-control {{ widget.attrs.class }}"
    type="{{ widget.type }}" 
    name="{{ widget.name }}"
    {% if widget.value != None %} 
        value="{{ widget.value|stringformat:'s' }}"
    {% endif %}
    {% include "django/forms/widgets/attrs.html" %}>

templates/django/forms/widgets/select.html
<select class="form-select" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
    <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
    {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
    </optgroup>{% endif %}{% endfor %}
</select>

templates/form_snippet.html
{% load add_attr %}

{% for field in form %} 
<div class="mb-3">
    {{ field.label_tag }} 
    {% if field.errors %}
        {{ field|add_attr:"class:is-invalid" }}
    {% else %}
        {{field }}
    {% endif %}
    <div class="invalid-feedback">
    {% for error in field.errors %}
        {{ error }}
    {% endfor %}
    </div>
</div>
{% endfor %}

templates/home.html
{% extends 'base.html' %} {% block content %} Hello world! this is Productly
{%endblock content %}